{% set name = "visisipy" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/visisipy-{{ version }}.tar.gz
  sha256: 47c08335add09a3cffdd784d3aa385f375b8b1e65bb1184aa382fadba106bd45

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.27,<2
    - versioningit
    - pip
  run:
    - python >={{ python_min }},<3.14
    - matplotlib-base
    - numba >=0.60.0
    - numpy
    - optiland >=0.5.6
    - scipy
    - typing_extensions >=4.12.2
    - zospy >=2.1.2

test:
  imports:
    - visisipy
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/MREYE-LUMC/visisipy
  summary: Accessible vision simulations in Python.
  license: MIT
  license_file: LICENSE.md
  doc_url: https://visisipy.readthedocs.io/
  dev_url: https://github.com/MREYE-LUMC/visisipy

extra:
  recipe-maintainers:
    - jwmbeenakker
    - crnh
